### ISSUE TITLE
Find a linux contributor

### ISSUE THREAD

**Issue by bhstahl** [BusterLabs/Partyshare#11]
I don't have a machine running linux, but I would love to release Partyshare for it. I need someone running linux who would be willing to help with:

1. Add linux to the build target #7 
2. Test the target to make sure everything works, fixing any bugs
3. Make it publicly downloadable #9

**Comment by vanguz** [comment]
I'm using Debian 8.8
I'm not a developer, but really want to know if there's a way I can help with this. I love this project and want it to grow.

**Comment by bhstahl** [comment]
Thanks @vanguz ! Would you be comfortable trying to build the linux target (#7)?

**Comment by vanguz** [comment]
Sure!
Do you think it's possible for you to help me out with some parts of the process?
I'm very "techy", but not developer and It's my firs time using electron.

**Comment by hexagon6** [comment]
@bhstahl I'd love to volunteer. I'm a developer running linux. Rather than doing that manually I'd propose to setup a build pipeline which does that automatically.

**Comment by bhstahl** [comment]
Wonderful, thank fore volunteering to help @hexagon6 ! A build/release pipeline sounds great, I'd like to have it for all targets. I'll add the OSX portion.

**Comment by bhstahl** [comment]
Once we have the linux target we're happy with, I'll link to that instead of this page [on the marketing site](https://github.com/BusterLabs/Partyshare/blob/e78a449d64c932e097bf91283e71676678dd959e/index.html#L39-L40) and we can close this ticket.

**Comment by bhstahl** [comment]
Closing this out now that we have @hexagon6 🎉
