### ISSUE TITLE
Add the folder to IPFS so you can share links with filenames

### ISSUE THREAD

**Issue by mattseh** [BusterLabs/Partyshare#23]
Hi,

Interesting project! I played with it and it's working well. A suggestion: When adding files, it links to the gateway with just a hash, it might be cool to have a "virtual folder", so that the link looks like /ipfs/hash/real_filename.txt

This way it's easier to know what the file is when sharing links.

Cheers

**Comment by bhstahl** [comment]
Good idea! Was actually thinking along the same lines as well. Thanks @mattseh !

**Comment by mattseh** [comment]
Related: It'd also be great to support subfolders, which behave like "ipfs add -r folder/", which gives the nice IPFS folder contents listing :)

**Comment by mattseh** [comment]
I wonder if there is an implicit privacy breach after these changes, before multiple files could be added, but there was no easy way for someone to list all files added by a user. Now that the Partyshare folder is treated as a single IPFS tree, it is trivial to see all files added.

**Comment by Fil** [comment]
Big time. Partyshare should give a directory wrapper around the file you ask to share, not an access to the PartyShare directory root.

**Comment by bhstahl** [comment]
While technically all the files are public, but exposing the file list isn't ideal. Opened #29 to fix that

**Comment by Fil** [comment]
Sure they have a hash that can be used to require them, but my understanding is that, if the hash isn't disseminated, the files aren't detectable at all, are never transferred, and are as good as private. (Aside from #29, the feature in #23 is really a pleasure to use.)

**Comment by mattseh** [comment]
@Fil IPFS DHT sniffing means files are never truly private.

That said, in Partyshare 1.1.0, if you add a file to the main folder or a subfolder, you can then easily view the root folder or a subfolder by editing the path.

**Comment by Fil** [comment]
I didn't know about DHT sniffing, thanks for pointing this out!
