### ISSUE TITLE
Inform about persistence of data on IPFS

### ISSUE THREAD

**Issue by xuv** [BusterLabs/Partyshare#24]
Correct me if I'm wrong but once you put files in IPFS, you can't delete them.
Since the app looks like a great way to share "private" files between friends. It might be useful to specify this: **Once shared, it can't be unshared.** or something in that vein.
What do you think? 

PS: Thanks for a great project that makes using IPFS in such a simple and appealing way.

**Comment by bhstahl** [comment]
Agreed, we should add that. Thanks for the kind words!
