### ISSUE TITLE
Outdated npm package dependencies

### ISSUE THREAD

**Issue by hexagon6** [BusterLabs/Partyshare#38]
It seems that the branch `add-with-querystrings` is not available anymore:

```bash
yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find match for "107c5c16162bf7c5f74d858ebc58644ea20924a5" in "_c" for "git://github.com/bhstahl/js-ipfs-api.git".
```
```package.json
...
  "ipfs-api": "git://github.com/bhstahl/js-ipfs-api.git#add-with-querystrings",
  "ipfsd-ctl": "git://github.com/bhstahl/js-ipfsd-ctl.git#add-with-querystrings",
...
```
@bhstahl can you update this? :+1:

**Comment by bhstahl** [comment]
Aha, that branch was actually merged into `js-ipfs-api` (https://github.com/ipfs/js-ipfs-api/pull/594), hence the deletion of the branch, so we can just update it back to the main repo instead of my fork
