### ISSUE TITLE
yarn release does not work on linux: GNU/sed syntax?

### ISSUE THREAD

**Issue by hexagon6** [BusterLabs/Partyshare#40]
I assume my sed version on Linux treats passed arguments differently than on OS X-based sed.

OK: `sed -i 's|replace this with|pattern|' file`

File not found: `sed -i '' 's|replace this with|pattern|' file`

```bash
$ yarn release
yarn run v1.3.2
$ yarn build_ui && yarn fix_asar && build --draft
$ webpack
Hash: effcf9a2630188edd252
...
$ sed -i '' 's|run(cmd, args|run(cmd.replace("app.asar", "app.asar.unpacked"), args|' node_modules/ipfsd-ctl/src/exec.js
sed: can't read s|run(cmd, args|run(cmd.replace("app.asar", "app.asar.unpacked"), args|: No such file or directory
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ ls node_modules/ipfsd-ctl/src/exec.js
node_modules/ipfsd-ctl/src/exec.js
```

**Comment by hexagon6** [comment]
Fixing the second argument lets `yarn release` run fine. The built `.deb` package installs just fine too.
It works definitely on Ubuntu 17.10. :fireworks: :champagne: @bhstahl

**Comment by hexagon6** [comment]
#41 contains a commit which fixes this issue on linux. @bhstahl Please try on OS X before merging

**Comment by hexagon6** [comment]
@bhstahl fixed it on my branch:
check it out:  https://github.com/hexagon6/Partyshare/releases
There is a Partyshare.deb for download available now :smile: 

Adjust travis-ci settings if you want to Pull this in for BusterLabs, since a Github API-token needs to be added.

**Comment by bhstahl** [comment]
Wahoo! I'm going to take a quick stab at seeing if I can remove that fix asap step first (https://github.com/BusterLabs/Partyshare/issues/14) since that would be ideal
