### ISSUE TITLE
Auto-update files not generated for linux build

### ISSUE THREAD

**Issue by bhstahl** [BusterLabs/Partyshare#53]
Building off of #47, linux builds are not generating the `latest-linux.{json,yml}` files

cc @hexagon6

**Comment by hexagon6** [comment]
@bhstahl nice! Unfortunately I don't see drafts. How can I test it beforehand? Upload it to ipfs? ;-)

**Comment by bhstahl** [comment]
Ah, right. Here it is https://gateway.ipfs.io/ipfs/QmZN3S1X8vSTbxaDPZm7X27bDp7yoYU9V9gguEZjRtNGim/partyshare.busterlabs.xyz-1.2.7-linux.deb

**Comment by hexagon6** [comment]
I guess, either we need to
A) disable auto-update for linux builds or
B) try to generate these files to get it working.

When testing your build, I get the following log output:

[partyshare.busterlabs.xyz-1.2.7-linux.log](https://github.com/BusterLabs/Partyshare/files/1504231/partyshare.busterlabs.xyz-1.2.7-linux.log)

The following happens when I run the build:
1. Partyshare opens a window
2. Connecting to ipfs...
3. Window disappears
4. terminal logs stays / process still runs.

**Comment by bhstahl** [comment]
I'm still worried about this though:

```sh
_connectToIPFS Error: non-zero exit code 255
  while running: /opt/Partyshare/resources/app.asar/node_modules/subcomandante/subcom 19399 /opt/Partyshare/resources/app.asar.unpacked/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon

  
    at ChildProcess.<anonymous> (/opt/Partyshare/resources/app.asar/node_modules/subcomandante/fork.js:21:23)
    at emitTwo (events.js:130:20)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

``

**Comment by bhstahl** [comment]
Alright, here's to hoping this works!

https://github.com/BusterLabs/Partyshare/releases/tag/v1.3.0

**Comment by bhstahl** [comment]
Realizing the `AppImage` file wasn't included in 1.3.0, which I think auto-update uses, so I just committed [`1.3.1`](https://github.com/BusterLabs/Partyshare/releases/tag/v1.3.1) to include it.

**Comment by hexagon6** [comment]
[partyshare.busterlabs.xyz-1.3.1-linux.log](https://github.com/BusterLabs/Partyshare/files/1504261/partyshare.busterlabs.xyz-1.3.1-linux.log)

3 Errors:
1) [23:10:27.052] [error] [ipcMain] No window to send event on

2) [23:10:27.248] [error] Error: Error: ENOENT: no such file or directory, open '/opt/Partyshare/resources/app-update.yml'

3) `[23:10:30.131] [error] [IPFSSync] _connectToIPFS Error: non-zero exit code 255`
`while running: /opt/Partyshare/resources/app.asar.unpacked/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon`

**Comment by hexagon6** [comment]
1) Probably because I use i3. Will try on GNOME-environment
2) how does your app-update.yml look like?
3) don't know. my first build worked, maybe the dependency version is a problem? https://github.com/hexagon6/Partyshare/blob/build-test2/package.json#L31
