### ISSUE TITLE
partysha.re expired and /example.gif in README is busted

### ISSUE THREAD

**Issue by jamiew** [BusterLabs/Partyshare#58]
Not news but filing for posterity! Domain names amirite! https://partysha.re

**Comment by bhstahl** [comment]
Unfortunately 101domains.com is trying to charge me a $150 late fee on top of the renewal fee. So, I'm moving bak to standard Github hosting at https://github.com/BusterLabs/Partyshare.

**Comment by jamiew** [comment]
Wow. Shameful on their part
