### ISSUE TITLE
Publish a linux target for download on partysha.re

### ISSUE THREAD

**Issue by bhstahl** [BusterLabs/Partyshare#9]
- [ ] Add download button to [index.html](https://github.com/BusterLabs/Partyshare/blob/133d067681af59a3e965525f1a4113bfd26b756a/index.html#L38-L40)
- [ ] Activate that download button with the latest release in [index.js](https://github.com/BusterLabs/Partyshare/blob/gh-pages/index.js)

**Comment by hexagon6** [comment]
Look . [here](https://github.com/hexagon6/Partyshare/blob/ci/automated-unices-builds/.travis.yml) . a demo-setup for . [automated](https://travis-ci.org/hexagon6/Partyshare) . [releases](https://github.com/hexagon6/Partyshare/releases) : #41
